# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Creates C++ loop 
#'
#' Meant to be a helper within date_check(), and subsequently propagate_date()
NULL

#' @param x Our date vector
#' @param y Our days supply vector
#' @return A new vector to be appended to a users dataframe with adjusted dates
#' @export
NULL

date_checkCpp <- function(x, y) {
    .Call(`_adheRenceRX_date_checkCpp`, x, y)
}

